spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # ?????? ?? ??? ???? drop?? ?? ????.
    properties:
      hibernate:
        #      show_sql: true   # System.out? ?????? ?? SQL? ???.
        format_sql: true
logging.level:
  org.hibernate.SQL: debug  # logger? ?? ?????? ?? SQL? ???.

server:
  port: 8888

jwt:
  issuer: s21011@gsm.hs.kr
  secret: GSMHsKr1234567890